trajectory_dataset:
    name: waymo_training_20s
    source: Waymo
    input_path: ./waymo_dataset/uncompressed_scenario_training_20s_training_20s.tfrecord-00001-of-01000
    scenario_index: 7

    # 55mph is roughly 25m/s.  100km/h is roughly 28m/s.
    speed_limit_mps: 28
