ppo:
  env_name: smarts
  seed: 42
  headless: True
  visdom: False
  neighborhood_radius: 55 # Radius (meter) for neighborhood vehicles
  rgb_meters: 64 # Height and width (meters) of RGB image in SMARTS observation
  rgb_pixels: 64 # Height and width (pixels) of RGB image in SMARTS observation  
  max_episode_steps: 200 # 20 seconds. Maximum steps per episode.
  num_stack: 4 # Number of frames to stack
  action_space_type: "Continuous"
  # action_space_type: "Lane"
  action_adapter: "discrete"
  # action_adapter: "lane"
  agent_ids: 
    - Bear1
  scenarios: 
    - loop
  initial_lr: 0.0003
  critic_loss_weight: 0.5
  gamma: 0.99 # Reward discount
  clip_ratio: 0.2
  nn: NeuralNetwork1
  # nn: NeuralNetwork2
  n_steps: 2000 # Horizon, a.k.a, trajectory length
  max_traj: 100000
  num_train_epochs: 3
  grad_batch: 256
  save_interval: 20
  mode: train # train or evaluate
  model_initial: False

  # Local
  # path_old_model: "/home/kyber/workspaces/training/cruiser_2021_10_17_02_00/models/ppo/cruiser_2021_10_17_06_03/13056"

  # Docker
  # path_old_model: "/src/training/cruiser_2021_10_17_02_00/models/ppo/cruiser_2021_10_17_06_03/13056"
