repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        stages: [push]
        args:
            [
            "--errors-only",
            "-rn", # Only display messages
            "-sn", # Don't display the score
            ]
        