smarts:
  seed: 42
  name: SB3
  visdom: False # If True, enables Visdom display.
  sumo_gui: False # If True, enables sumo-gui display.

  # Environment
  n_stack: 4 # Number of frames to stack as input to policy network
  train_steps: 1e8 # Number of training steps.
  checkpoint_freq: 1e5 # Save a model every checkpoint_freq calls to env.step().
  eval_eps: 3 # Number of evaluation epsiodes.
  eval_freq: 1e5 # Evaluate the trained model every eval_freq steps and save the best model.
  
  # Policy
  feature_extractor_class: CFEL5Kit

  # PPO hyperparameter
  alg: PPO
  hyperparameter:
    lr: 3e-4
    num_rollout_steps: 256
    gamma: 0.8
    gae_lambda: 0.9
    n_epochs: 10
    seed: 42
    batch_size: 64


