smarts:
  seed: 42
  name: SB3
  visdom: False # If True, enables Visdom display.
  sumo_gui: False # If True, enables sumo-gui display.

  n_stack: 4 # Number of frames to stack as input to policy network
  train_steps: 1e8 # Number of training steps.
  feature_extractor_class: CFEL5Kit

  checkpoint_freq: 1e5 # Save a model every checkpoint_freq calls to env.step().
  eval_eps: 3 # Number of evaluation epsiodes.
  eval_freq: 1e5 # Evaluate the trained model every eval_freq steps and save the best model.
  # video_length: 3e3 # Length of video in number of frames