smarts:
  # Environment
  seed: 42
  name: SB3
  visdom: False # If True, enables Visdom display.
  sumo_gui: False # If True, enables sumo-gui display.
  img_meters: 64
  img_pixels: 112
  n_stack: 1 # Number of frames to stack as input to policy network
  
  # Training
  train_steps: 1e8 # Number of training steps.
  checkpoint_freq: 1e5 # Save a model every checkpoint_freq calls to env.step().
  eval_eps: 5 # Number of evaluation epsiodes.
  eval_freq: 1e5 # Evaluate the trained model every eval_freq steps and save the best model.

  # Policy
  alg: PPO
  policy: l5kit
  # policy: dreamer
  # policy: naturecnn
  # policy: customnaturecnn
  # policy: r2plus1d_18
