levels:
  no-traffic-south-west:
    train:
      total: 18
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        3lane_t:
          percent: 0.25
          specs: [[50kmh,no-traffic,0.5], [100kmh,no-traffic,0.5]]
          stops: null
          bubbles: null
        3lane_c:
          percent: 0.25
          specs: [[50kmh,no-traffic,0.5], [100kmh,no-traffic,0.5]]
          stops: null
          bubbles: null
        4lane_t:
          percent: 0.25
          specs: [[50kmh,no-traffic,0.5], [100kmh,no-traffic,0.5]]
          stops: null
          bubbles: null
        4lane_c:
          percent: 0.25
          specs: [[50kmh,no-traffic,0.5], [100kmh,no-traffic,0.5]]
          stops: null
          bubbles: null
    test:
      total: 0
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
          percent: 0.5
          specs: [[70kmh,no-traffic,1.0]]
          stops: null
          bubbles: null
        2lane_c:
          percent: 0.5
          specs: [[70kmh,no-traffic,1.0]]
          stops: null
          bubbles: null
  no-traffic-east-south:
    train:
      total: 18
      ego_missions:
        # left turn from south to west
      - start: east-EW
        end:  south-NS
      intersection_types:
        3lane_t:
          percent: 0.25
          specs: [[50kmh,no-traffic,0.5], [100kmh,no-traffic,0.5]]
          stops: null
          bubbles: null
        3lane_c:
          percent: 0.25
          specs: [[50kmh,no-traffic,0.5], [100kmh,no-traffic,0.5]]
          stops: null
          bubbles: null
        4lane_t:
          percent: 0.25
          specs: [[50kmh,no-traffic,0.5], [100kmh,no-traffic,0.5]]
          stops: null
          bubbles: null
        4lane_c:
          percent: 0.25
          specs: [[50kmh,no-traffic,0.5], [100kmh,no-traffic,0.5]]
          stops: null
          bubbles: null
    test:
      total: 0
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
      intersection_types:
        2lane_t:
          percent: 0.5
          specs: [[70kmh,no-traffic,1.0]]
          stops: null
          bubbles: null
        2lane_c:
          percent: 0.5
          specs: [[70kmh,no-traffic,1.0]]
          stops: null
          bubbles: null
