trajectory_dataset:
    name: 
    source: Waymo
    input_path: ./training_20s/uncompressed_scenario_training_20s_training_20s.tfrecord-00000-of-01000

    # 55mph is roughly 25m/s.  100km/h is roughly 28m/s.
    speed_limit_mps: 28
    flip_y: False
    swap_xy: False

    map_net:
        # These are dimensions of the Sumo network in map.net.xml.
        # We map the coordinates in the input dataset onto this space.
        # max_y is required if flip_y since True.
        max_y: 34.7472

        # The map width is used to filter position_x values
        # to ensure they're in range.
        width: 310.91886
