ppo_gae:
  env_name: smarts
  seed: 42
  headless: True
  visdom: False
  neighborhood_radius: 55 # Radius (meter) for neighborhood vehicles
  rgb_wh: 110 # Height and width (meter) of RGB image in SMARTS observation
  max_episode_steps: 200 # 3 minutes. Maximum steps per episode.
  num_stack: 4 # Number of frames to stack
  num_skip: 1 # Frequency of frames to be stacked
  action_space_type: "Continuous"
  # action_space_type: "Lane"
  action_adapter: "discrete"
  # action_adapter: "lane"
  agent_ids: 
    - Bear1
  scenarios: 
    - loop

  # Observation and action space
  observation1_dim: [256, 256, 12] # rgb image * num_stack
  observation2_dim: [8] # [steering, speed] * num_stack
  action_dim: 5 # Discrete  
  # action_dim: 4 # Lane
  
  
  # Optimizer
  actor_lr: 0.0003
  critic_lr: 0.001

  # PPO
  gamma: 0.99 # Reward decay
  lam: 0.97 # Advantage decay
  clip_ratio: 0.2
  target_kl: 0.01

  # NeuralNetwork
  # nn: NeuralNetwork1
  nn: NeuralNetwork2

  # Iteration size
  n_steps: 4000 # Horizon, a.k.a, trajectory length
  max_traj: 100000
  actor_train_epochs: 80
  critic_train_epochs: 80

  # Gradient batch size
  grad_batch: 256

  # Models and logs
  save_interval: 20
  mode: train # train or evaluate
  model_initial: False

  # Local
  # path_old_actor: "/home/kyber/workspaces/SMARTS/training/cruiser_2021_10_17_02_00/models/ppo_gae/actor_2021_10_17_06_03/13056"
  # path_old_critic: "/home/kyber/workspaces/SMARTS/training/cruiser_2021_10_17_02_00/models/ppo_gae/critic_2021_10_17_06_03/13056"

  # Docker
  # path_old_actor: "/src/training/cruiser_2021_10_17_02_00/models/ppo_gae/actor_2021_10_17_06_03/13056"
  # path_old_critic: "/src/training/cruiser_2021_10_17_02_00/models/ppo_gae/critic_2021_10_17_06_03/13056"
