smarts:
  seed: 42
  name: SB3
  visdom: False # If True, enables Visdom display.
  sumo_gui: False # If True, enables sumo-gui display.
  rgb_meters: 100 # Height and width (meters) of RGB image in SMARTS observation
  rgb_pixels: 100 # Height and width (pixels) of RGB image in SMARTS observation  
  eval_eps: 800 # Number of evaluation epsiodes.
