smarts:
  seed: 42
  name: SB3
  visdom: False # If True, enables Visdom display.
  sumo_gui: False # If True, enables sumo-gui display.
  rgb_meters: 100 # Height and width (meters) of RGB image in SMARTS observation
  rgb_pixels: 100 # Height and width (pixels) of RGB image in SMARTS observation  
  eval_eps: 10 # Number of evaluation epsiodes.
  checkpoint_freq: 1e3 # Save a model every checkpoint_freq calls to env.step().
  train_steps: 1e4 # Number of training steps.
