smarts:
  seed: 42
  name: SB3
  visdom: False # If True, enables Visdom display.
  sumo_gui: False # If True, enables sumo-gui display.

  n_stack: 5 # Number of frames to stack as input to policy network
  train_steps: 1e4 # Number of training steps.

  checkpoint_freq: 1e3 # Save a model every checkpoint_freq calls to env.step().
  eval_eps: 10 # Number of evaluation epsiodes.
  eval_freq: 1e3 # Evaluate the trained every eval_freq steps and save the best model.