env_para:
  env_name: SMARTS
  seed: 42
  headless: True
  visdom: False
  neighborhood_radius: 55 # Radius (meter) for neighborhood vehicles
  rgb_wh: 110 # Height and width (meter) of RGB image in SMARTS observation
  max_episode_steps: 1800 # 3 minutes. Maximum steps per episode.
  agent_ids: 
    - predator1
    # - predator2
    # - predator3
    - prey1
    # - prey2
  controller: Categorical
  scenarios: 
    # - /home/kyber/workspaces/SMARTS/scenarios/cloverleaf
    # - /home/a84166141/workspaces/SMARTS/scenarios/cloverleaf
    # - /home/adai/workspaces/SMARTS/scenarios/cloverleaf    
    - /src/scenarios/cloverleaf

model_para:
  # Observation and action space
  observation_dim: [256, 256, 9]
  action_dim: 5
  
  # Optimizer
  initial_lr_predator: 0.001
  initial_lr_prey: 0.0005

  # PPO
  critic_loss_weight: 0.5
  entropy_loss_weight: 0.09 # 0.01
  entropy_loss_discount_rate: 1 # 0.995
  gamma: 0.99 # Reward discount
  clip_value: 0.2

  # Iteration size
  batch_size: 128 # Horizon, a.k.a, trajectory length
  max_batch: 10000000
  num_train_epochs: 3

  # Models and logs
  save_interval: 25
  mode: train # train or evaluate
  model_initial: False

  # Local
  # tensorboard_path: "/home/adai/workspaces/SMARTS/examples/gameOfTag/logs/"
  # model_path: "/home/adai/workspaces/SMARTS/examples/gameOfTag/models/"
  # model_predator: "/home/adai/workspaces/SMARTS/examples/gameOfTag/models/predator_2021_10_10_04_27/100"
  # model_prey: "/home/adai/workspaces/SMARTS/examples/gameOfTag/models/prey_2021_10_10_04_27/100"

  # Docker
  tensorboard_path: "/src/examples/gameOfTag/logs/"
  model_path: "/src/examples/gameOfTag/models/"

# minibatch / epoch = 3-15
# batch size M = 64-4096 
# trajectory length / horizon = 128-2048
