env_para:
  env_name: SMARTS
  headless: True
  neighborhood_radius: 80 # Radius (meter) for neighborhood vehicles
  rgb_wh: 110 # Height and width (meter) of RGB image in SMARTS observation
  max_episode_steps: 1800 # 3 minutes. Maximum steps per episode. When using ContinueEpisode wrapper, ensure: max_episode_steps > agent_para.agent_config.max_steps .
  agent_num: 5
  agent_ids: 
    - predator1
    - predator2
    - predator3
    - prey1
    - prey2
  controller: Continuous
  scenarios: 
    - /home/kyber/workspaces/SMARTS/scenarios/cloverleaf
    # - /home/kyber/workspaces/SMARTS/scenarios/figure_eight
    # - /src/scenarios/cloverleaf
    # - /src/scenarios/figure_eight


model_para:
  state_dim: [256, 256, 3]
  action_dim: 3 
  
  initial_lr_predator: 0.001
  initial_lr_prey: 0.0005

  critic_loss_weight: 0.5
  entropy_loss_weight: 0.01
  ent_discount_rate: 0.995
  gamma: 0.99
  clip_value: 0.2

  batch_size: 64
  max_batch: 100000000
  num_train_epochs: 10

  save_interval: 50
  eval_interval: 50
  
  # filter_arches: # A=421,108 # CNN layers [#filters, [filter_w, filter_h], [stride_w, stride_h]]
  #   - [16, [32, 32], [4, 4]]
  #   - [32, [17, 17], [4, 4]]
  #   - [64, [3, 3], [2, 2]] 
  # hidden_sizes: [128] # MLP layers 
  # filter_arches: # B=502,836 # CNN layers [#filters, [filter_w, filter_h], [stride_w, stride_h]]
  #   - [16, [32, 32], [4, 4]]
  #   - [32, [17, 17], [2, 2]]
  #   - [64, [7, 7], [2, 2]] 
  #   - [128, [4,4], [2, 2]]
  # hidden_sizes: [64] # MLP layers 
  # filter_arches: # C=211,049 # CNN layers [#filters, [filter_w, filter_h], [stride_w, stride_h]]
  #   - [5, [12, 12], [4, 4]]
  #   - [16, [6, 6], [4, 4]]
  #   - [32, [3, 3], [2, 2]] 
  # hidden_sizes: [256] # MLP layers 

benchmark:
  base_path: "/home/kyber/workspaces/" # For use in local computer
  # base_path: "/" # For use in server
  # checkpoint_predator: /got/models/predator/
  # checkpoint_prey: /got/models/prey/
