env_para:
  env_name: SMARTS
  headless: True
  neighborhood_radius: 80 # Radius (meter) for neighborhood vehicles
  rgb_wh: 110 # Height and width (meter) of RGB image in SMARTS observation
  max_episode_steps: 1800 # 3 minutes. Maximum steps per episode. When using ContinueEpisode wrapper, ensure: max_episode_steps > agent_para.agent_config.max_steps .
  agent_num: 5
  agent_ids: 
    - predator1
    - predator2
    - predator3
    - prey1
    - prey2
  controller: Continuous
  scenarios: 
    # - /home/kyber/workspaces/SMARTS/scenarios/cloverleaf
    # - /home/kyber/workspaces/SMARTS/scenarios/figure_eight
    - /src/scenarios/cloverleaf
    - /src/scenarios/figure_eight


model_para:
  state_dim: [256, 256, 3]
  action_dim: 5 # action_dim=3 for action_type=DiagGaussian; action_dim=5 for action_type=Categorical; action_dim=12 for controller=LaneWithContinuousSpeed
  num_episodes: 10000000 # Maximum number of episodes over which to train
  initial_lr_predator: 3e-4
  initial_lr_prey: 9e-5
  discount_factor: 0.99
  gae_lambda: 0.95
  ppo_epsilon: 0.2
  value_scale: 0.5
  entropy_scale: 0.01
  # horizon: 128
  num_epochs: 10
  batch_size: 128
  # num_envs: 16
  save_interval: 10
  eval_interval: 10
  activation: leaky_relu
  # filter_arches: # A=421,108 # CNN layers [#filters, [filter_w, filter_h], [stride_w, stride_h]]
  #   - [16, [32, 32], [4, 4]]
  #   - [32, [17, 17], [4, 4]]
  #   - [64, [3, 3], [2, 2]] 
  # hidden_sizes: [128] # MLP layers 
  # filter_arches: # B=502,836 # CNN layers [#filters, [filter_w, filter_h], [stride_w, stride_h]]
  #   - [16, [32, 32], [4, 4]]
  #   - [32, [17, 17], [2, 2]]
  #   - [64, [7, 7], [2, 2]] 
  #   - [128, [4,4], [2, 2]]
  # hidden_sizes: [64] # MLP layers 
  filter_arches: # C=211,049 # CNN layers [#filters, [filter_w, filter_h], [stride_w, stride_h]]
    - [5, [12, 12], [4, 4]]
    - [16, [6, 6], [4, 4]]
    - [32, [3, 3], [2, 2]] 
  hidden_sizes: [256] # MLP layers 

benchmark:
  # checkpoint_predator: /got/models/predator/
  # checkpoint_prey: /got/models/prey/
