# smarts/benchmark/competition_v0/config.yaml
---
benchmark:
  name: "Driving SMARTS V0"
  auto_install: true
  eval_episodes: 2
  shared_env_params:
    seed: 42
    headless: true
    action_space: "RelativeTargetPose" # we can only allow `RelativeTargetPose` and `TargetPose`
  standard_env:
    env: "smarts.env:driving-smarts-competition-v0"
    scenarios:
      - 1_to_2lane_left_turn_c
      - 1_to_2lane_left_turn_t
      - 3lane_merge_multi_agent
      - 3lane_merge_single_agent
      - 3lane_cruise_multi_agent
      - 3lane_cruise_single_agent
      - 3lane_cut_in
      - 3lane_overtake
  bubble_env: # Should be more stable with incoming bubble fixes
    env: "smarts.env:driving-smarts-competition-bubble-env-v0"
    scenarios:
      - 6
      - 4
      - 42
  naturalistic_env: # reserved for driving_smarts_competition_naturalistic-v0
    scenario_dirs:
      - "./scenarios/naturalistic/waymo"
      - "./scenarios/naturalistic/ngsim"
  agent:
    interface:
      max_episode_steps: 1000
      img_meters: 50 # Observation image area size in meters.
      img_pixels: 112 # Observation image size in pixels.
    locator: "smarts.zoo:competition-baseline-v0"
    params:
      speed: 20 # Provided to the agent