smarts:
  # Environment
  seed: 42
  name: SB3
  visdom: False # If True, enables Visdom display.
  sumo_gui: False # If True, enables sumo-gui display.
  img_meters: 50
  img_pixels: 112
  n_stack: 3 # Number of frames to stack as input to policy network
  action_space: Continuous # Either "Lane" or "Continuous"
  action_wrapper: Discrete # Either "Lane" or "Continuous" or "Discrete"
  observation_wrapper: "ObsCNN" # Either "ObservationCNN" or "ObservationMLP"
  # observation_wrapper: "ObsMLP" # Either "ObservationCNN" or "ObservationMLP"

  # Training
  train_steps: 1e8 # Number of training steps.
  checkpoint_freq: 1e5 # Save a model every checkpoint_freq calls to env.step().
  eval_eps: 50 # Number of evaluation epsiodes.
  eval_freq: 1e5 # Evaluate the trained model every eval_freq steps and save the best model.

  # Policy
  alg: PPO
  # alg: DQN
  
  policy: naturecnn
  # policy: customnaturecnn
  # policy: mlp
  # policy: l5kit
  # policy: dreamer
  # policy: r2plus1d_18
  # policy: dqn_naturecnn