dreamerv2:
  env_name: smarts
  seed: 42
  headless: True
  visdom: False
  neighborhood_radius: 55 # Radius (meter) for neighborhood vehicles
  rgb_wh: 110 # Height and width (meter) of RGB image in SMARTS observation
  max_episode_steps: 200 # 20 seconds. Maximum steps per episode.
  action_space_type: "continuous"
  # action_space_type: "lane"
  # action_space_type: "discrete"
  agent_ids: 
    - Tigger1
  scenarios: 
    - /home/kyber/workspaces/SMARTS/scenarios/loop
    # - /src/scenarios/loop

  # Observation and action space
  # observation1_dim: [256, 256, 12] # rgb image * num_stack
  # observation2_dim: [8] # [steering, speed] * num_stack
  # action_dim: 4 # Lane
  # action_dim: 0 # LaneWithContinuousSpeed
  # action_dim: 5 # Discrete
  action_dim: 3 # Continuous    
  
  # Iteration size
  n_steps: 4000 # Horizon, a.k.a, trajectory length
  max_traj: 100000
  num_train_epochs: 3

  # Gradient batch size
  grad_batch: 256

  # Models and logs
  save_interval: 20
  mode: train # train or evaluate
  model_initial: False

  # Local
  path_tensorboard: "/home/kyber/workspaces/SMARTS/examples/auto_drive/logs/"
  path_new_model: "/home/kyber/workspaces/SMARTS/examples/auto_drive/models/"
  # path_old_model: "/home/kyber/workspaces/training/cruiser_2021_10_17_02_00/models/cruiser_2021_10_17_06_03/13056"

  # Docker
  # path_tensorboard: "/src/examples/auto_drive/logs/"
  # path_new_model: "/src/examples/auto_drive/models/"
