dreamerv2:
  env_name: smarts
  seed: 42
  headless: True
  visdom: False
  neighborhood_radius: 55 # Radius (meter) for neighborhood vehicles
  rgb_wh: 110 # Height and width (meter) of RGB image in SMARTS observation
  max_episode_steps: 200 # 20 seconds. Maximum steps per episode.
  action_space_type: "Continuous"
  # action_space_type: "Lane"
  action_adapter: "continuous"
  # action_adapter: "lane"
  # action_adapter: "discrete"
  agent_ids: 
    - Rabbit1
  scenarios: 
    - loop
  n_steps: 1000 # Horizon, a.k.a, trajectory length
  max_traj: 100000
  num_train_epochs: 3
  grad_batch: 256
  save_interval: 20
  mode: train # train or evaluate
  model_initial: False

  # Local
  # path_old_model: "/home/kyber/workspaces/training/cruiser_2021_10_17_02_00/models/dreamerv2/cruiser_2021_10_17_06_03/13056"

  # Docker
  # path_old_model: "/src/training/cruiser_2021_10_17_02_00/models/dreamerv2/cruiser_2021_10_17_06_03/13056"
