dreamerv2:
  env_name: smarts
  seed: 42
  headless: True
  visdom: False
  neighborhood_radius: 30 # Radius (meter) for neighborhood vehicles
  rgb_meters: 64 # Height and width (meters) of RGB image in SMARTS observation
  rgb_pixels: 64 # Height and width (pixels) of RGB image in SMARTS observation  
  max_episode_steps: 300 # 30 seconds. Maximum steps per episode.
  action_space_type: "Continuous"
  # action_space_type: "Lane"
  action_adapter: "continuous"
  # action_adapter: "lane"
  # action_adapter: "discrete"
  agent_ids: 
    - Rabbit1
  scenarios: 
    - loop
  mode: train # train or evaluate

  # Local
  # path_old_model: "/home/kyber/workspaces/training/cruiser_2021_10_17_02_00/models/dreamerv2/cruiser_2021_10_17_06_03/13056"

  # Docker
  # path_old_model: "/src/training/cruiser_2021_10_17_02_00/models/dreamerv2/cruiser_2021_10_17_06_03/13056"
