tasks:
  # task00 and task00-multiagent are for unit testing purposes only
  task00: # unittest
    easy:
      train: "../tests/task/train_task00_easy*"
      test:  "../tests/task/test_task00_easy*"
    eval_test:
      train: "../tests/task/eval_test/train_task00_eval_test*"
      test:  "../tests/task/eval_test/test_task00_eval_test*"
  task00-multiagent: # unittest
    easy:
      train: "../tests/task/train_task00-multiagent_easy*"
      test:  "../tests/task/test_task00-multiagent_easy*"
    eval_test:
      train: "../tests/task/eval_test_multiagent/train_task00-multiagent_eval_test*"
      test:  "../tests/task/eval_test_multiagent/test_task00-multiagent_eval_test*"
  task00-curriculum: # unittest
    test_grade1:
      train: "../tests/curriculum_test/train_test_grade1*"
      test:  "../tests/curriculum_test/test_test_grade1*"
    test_grade2:
      train: "../tests/curriculum_test/train_test_grade2*"
      test:  "../tests/curriculum_test/test_test_grade2*"
    test_grade3:
      train: "../tests/curriculum_test/train_test_grade3*"
      test:  "../tests/curriculum_test/test_test_grade3*"
    no-traffic:
      train: "../tests/curriculum_test/train_no-traffic*"
      test: "../tests/curriculum_test/test_no-traffic*"
    low-density:
      train: "../tests/curriculum_test/train_low-density*"
      test: "../tests/curriculum_test/test_low-density*"
    mid-density:
      train: "../tests/curriculum_test/train_mid-density*"
      test: "../tests/curriculum_test/test_mid-density*"
    high-density:
      train: "../tests/curriculum_test/train_high-density*"
      test: "../tests/curriculum_test/test_high-density*"
      
  # Format of generated scenario directory:
  #   train: <path_to_train_scenarios>/train_<task_id>_<level_id>*
  #   test: <path_to_test_scenarios>/train_<task_id>_<level_id>*
  taskX:
    road-blocks:
      train: "scenarios/taskX/train_taskX_road-blocks*"
      test:  "scenarios/taskX/test_taskX_road-blocks*"
    bubbles:
      train: "scenarios/taskX/train_taskX_bubbles*"
      test:  "scenarios/taskX/test_taskX_bubbles*"
    intersection-specific:
      train: "scenarios/taskX/train_taskX_intersection-specific*"
      test:  "scenarios/taskX/test_taskX_intersection-specific*"
  task1:
    no-traffic:
      train: "scenarios/task1/train_task1_no-traffic*"
      test:  "scenarios/task1/test_task1_no-traffic*"
    simple:
      train: "scenarios/task1/train_task1_simple*"
      test:  "scenarios/task1/test_task1_simple*"
    easy:
      train: "scenarios/task1/train_task1_easy*"
      test:  "scenarios/task1/test_task1_easy*"
    medium:
      train: "scenarios/task1/train_task1_medium*"
      test:  "scenarios/task1/test_task1_medium*"
    hard:
      train: "scenarios/task1/train_task1_hard*"
      test:  "scenarios/task1/test_task1_hard*"
  task2:
    low-high:
      train: "scenarios/task2/train_task2_low-high*"
      test:  "scenarios/task2/test_task2_low-high*"
    high-low:
      train: "scenarios/task2/train_task2_high-low*"
      test:  "scenarios/task2/test_task2_high-low*"
  taskgb:
    grade1:
      train: "scenarios/taskgb/train_grade1*"
      test: "scenarios/taskgb/test_grade1*"
    grade2:
      train: "scenarios/taskgb/train_grade2*"
      test: "scenarios/taskgb/test_grade2*"
    grade3:
      train: "scenarios/taskgb/train_grade3*"
      test: "scenarios/taskgb/test_grade3*"
    grade4:
      train: "scenarios/taskgb/train_grade4*"
      test: "scenarios/taskgb/test_grade4*"
    # Reserved for scenarios that are been dynamically added
    no-traffic:
      train: "scenarios/taskgb/train_no-traffic*"
      test: "scenarios/taskgb/test_no-traffic*"
    low-density:
      train: "scenarios/taskgb/train_low-density*"
      test: "scenarios/taskgb/test_low-density*"
    mid-density:
      train: "scenarios/taskgb/train_mid-density*"
      test: "scenarios/taskgb/test_mid-density*"
    high-density:
      train: "scenarios/taskgb/train_high-density*"
      test: "scenarios/taskgb/test_high-density*"
    constant-flow:
      train: "scenarios/taskgb/train_constant-flow*"
      test:  "scenarios/taskgb/test_constant-flow*"
  task3:
    easy:
      train: "scenarios/task3/train_task3_easy*"
      test:  "scenarios/task3/test_task3_easy*"
    medium:
      train: "scenarios/task3/train_task3_medium*"
      test:  "scenarios/task3/test_task3_medium*"
    hard:
      train: "scenarios/task3/train_task3_hard*"
      test:  "scenarios/task3/test_task3_hard*"
