agent:
  interface:
    max_episode_steps: 1000
    img_meters: 50 # Observation image area size in meters.
    img_pixels: 112 # Observation image size in pixels.
  locator: "smarts.zoo:competition-baseline-v0"
  params:
    speed: 20 # Provided to the agent