observation:
  events: 
    collisions: 5 # List[Collisions()]
  ego_vehicle_state:
    mission:
      route_vias: 5 # List[str]
      entry_tactic: 
        exclusion_prefixes: 5 # List[str]
      via: 5 # List[Via()]
  neighborhood_vehicle_states: 5 # List[VehicleObservation()]
  waypoint_paths: [5, 5] # List[List[Waypoint()]]
  lidar_point_cloud: [3, 3, 3] 
                      # Tuple[ 
                      #   List[np.ndarray], 
                      #   List[np.ndarray], 
                      #   List[Tuple[np.ndarray, np.ndarray]] 
                      # ]
  road_waypoints:
    lanes: 5 # List[Waypoint()]
    route_waypoints: 5 # List[Waypoint()]
  via_data: 
    near_via_points: 5 # List[ViaPoint()]
    hit_via_points: 5 # List[ViaPoint()] 
