observation:
  events: 
    collisions: 10 # List[Collisions("collidee_id", str)]
  ego_vehicle_state:
    mission:
      route_vias: 10 # List[str]
      entry_tactic:
        exclusion_prefixes: 10 # List[str]
      via: 10 # List[Via()]
    linear_velocity: 10 # np.ndarray(10,1) 
    angular_velocity: 10 # np.ndarray(10,1) 
    linear_acceleration: 10 # np.ndarray(10,1) 
    angular_acceleration: 10 # np.ndarray(10,1) 
    linear_jerk: 10 # np.ndarray(10,1) 
    angular_jerk: 10 # np.ndarray(10,1)
  neighborhood_vehicle_states: 10 # List[VehicleObservation()]
  waypoint_paths: [10, 10] # List[List[Waypoint()]]
  lidar_point_cloud: [10,10,[10,10]] # 
    #Tuple[ <----- CHECK LENGTH
    #     List[np.ndarray], <----- CHECK LENGTH
    #     List[np.ndarray],  <----- CHECK LENGTH
    #     List[Tuple[np.ndarray, np.ndarray]] <----- CHECK LENGTH
    # ]
  drivable_area_grid_map:  
    data: 10 # np.ndarray
  occupancy_grid_map:
    data: 10 # np.ndarray 
  top_down_rgb:
    data: 10 # np.ndarray
  road_waypoints:
    lanes: 10 # List[Waypoint()]
    route_waypoints: 10 # List[Waypoint()]
  via_data: 
    near_via_points: 10 # List[ViaPoint()]
    hit_via_points: 10 # List[ViaPoint()] 
