name: SMARTS CI Format

on: [push, pull_request]

env:
  venv_dir: .venv

jobs:
  test-formatting:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    container: huaweinoah/smarts:v0.4.18-minimal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Black code format
        run: |
          cd $GITHUB_WORKSPACE
          pip install --upgrade pip
          pip install black==20.8b1
          apt-get update && apt-get install -y curl
          apt-get install -y ca-certificates
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
          black --check .
          npx prettier --check envision/web/src

  test-docstring:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    container: huaweinoah/smarts:v0.4.18-minimal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check docstring
        run: |
          cd $GITHUB_WORKSPACE
          pip install --upgrade pip
          pip install pylint
          pylint -d all \
            -e missing-function-docstring \
            -e missing-class-docstring \
            -s n \
            --ignore marl_benchmark,examples,scenarios,docs,manager_pb2_grpc.py,worker_pb2_grpc.py \
            --msg-template='{path}: line {line}: {msg_id}: {msg}' \
            ./smarts ./envision
