name: readthedocs-auto-build

on: 
  schedule:
    - cron: '0 23 * * 1'
      # Runs at 11.00pm, UTC, every Monday
  push:
    branches:
      - readthedocs
  release:
    branches:
      - readthedocs
  merge_group:
    branches:
      - readthedocs

jobs:
  readthedocs-auto-build:
    runs-on: ubuntu-18.04
    container: huaweinoah/smarts:v0.4.18-minimal
    steps:
     - name: build_docs
       run: |
       curl -X POST -d "branches=readthedocs" -d "token=49d4cffb2612080723457da836c3bb29503c83e2" https://readthedocs.org/api/v2/webhook/smarts-readthedocs/212767/