smarts:
  env_name: smarts
  seed: 42
  headless: True
  visdom: False
  neighborhood_radius: 30 # Radius (meter) for neighborhood vehicles
  rgb_meters: 100 # Height and width (meters) of RGB image in SMARTS observation
  rgb_pixels: 100 # Height and width (pixels) of RGB image in SMARTS observation  
  max_episode_steps: 300 # 30 seconds. Maximum steps per episode.
  action_space_type: "Continuous"
  # action_space_type: "Lane"
  action_adapter: "continuous"
  # action_adapter: "lane"
  # action_adapter: "discrete"
  agent_ids: 
    - Tiger1
  scenarios: 
    - loop
  mode: train # train or evaluate
  logdir_evaluate: "/home/kyber/workspaces/SMARTS/examples/dreamer/logs/dreamerv2/dreamerv2_2021_10_17_06_03"
